apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-books-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-books
  template:
    metadata:
      labels:
        app: api-books
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: api-books
        image: southamerica-east1-docker.pkg.dev/poc-ipnet-cloud/cafe-com-cloud/cafe-com-cloud:be3cc56
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{"default": "my-backendconfig"}'
  labels:
    app: api-books
  name: api-books-svc
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: api-books
  

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-books-ing
spec:
  rules:
  - http:
      paths:
      - path: /books
        pathType: ImplementationSpecific
        backend:
          service:
            name: api-books-svc
            port:
              number: 5000
              
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: my-backendconfig
spec:
  healthCheck:
    requestPath: /books
